export default [
  "crisis",
  "catastrophic",
  "disaster",
  "meltdown",
  "collapse",
  "weak",
  "panic",
  "bombshell",
  "devastating",
  "collapse",
  "explosion",
  "loss",
  "unprecedented",
  "unstable",
  "warning signs",
  "believe",
  "sources say",
  "experts believe",
  "insiders claim",
  "rumors are circulating",
  "reports suggest",
  "industry insiders say",
  "confidential sources",
  "unconfirmed reports",
  "unverified information",
  "allegedly",
  "worst",
  "never before seen",
  "biggest ever",
  "massive sell-off",
  "unstoppable decline",
  "out of control",
  "skyrocketing risk",
  "unbearable losses",
  "worst hit",
  "extreme volatility",
  "record-breaking drops",
  "rogue investors",
  "end of days",
  "market manipulation",
  "pump and dump",
  "insider trading",
  "crash imminent",
  "hidden agenda",
  "shock to the system",
  "conspiracy",
  "under the radar",
  "wall street is hiding something",
  "they",
  "deceptive tactics",
  "act now",
  "hurry",
  "missing out",
  "time is running out",
  "the clock is ticking",
  "sell now",
  "urgent",
  "sell signal",
  "high-risk",
  "high-reward",
  "high-risk, high-reward",
  "prepare for the worst",
  "brace yourself for impact",
  "blockchain",
  "AI-driven stocks",
  "next big thing",
  "revolutionary technology",
  "disruptive innovation",
  "unmatched growth",
  "guaranteed return",
  "extraordinary growth potential",
  "financial freedom",
  "game-changer",
  "could",
  "may",
  "might",
  "could be on the verge of",
  "looks like",
  "rumors point to",
  "is poised to",
  "speculation is rampant",
  "could lead to",
  "expected to soar/fall",
  "market rigging",
  "corruption",
  "manipulated data",
  "shady dealings",
  "dirty tricks",
  "unethical practices",
  "untrustworthy company",
  "scam alert",
  "fraudulent claims",
  "illegal activity",
  "the elites are controlling the market",
  "hidden truth",
  "shadow economy",
  "under-the-table deals",
  "hiding the truth",
  "want you to know",
  "behind closed doors",
  "dark web",
  "fake news",
  "uncontrollable volatility",
  "imminent recession",
  "deflationary pressures",
  "hyperinflation risk",
  "total market crash",
  "black swan",
  "economic meltdown",
  "downturn coming",
  "recession is inevitable",
  "bubble bursting",
  "everything is fine, but...",
  "the market is bullish, however...",
  "on one hand... but on the other hand...",
  "positive outlook, but some analysts disagree",
  "growth potential despite risks",
  "uncertainty around the economy",
  "experts are divided",
  "short-term volatility",
  "day trading hype",
  "get rich quick",
  "hot stock",
  "price action",
  "predictions",
  "feud",
  "sceptics",
  "weigh down",
  "sues",
  "edges",
  "fell",
  "lower",
  "fall",
  "illegal",
  "illegally",
  "sudden",
  "drop",
  "junk",
  "cut",
  "hard",
  "agonizing",
  "panic",
  "sell-off",
  "chaos",
  "volatility",
  "instability",
  "uncertainty",
  "jeopardy",
  "illusion",
  "blunder",
  "mirage",
  "nightmare",
  "Broadband",
  "bubble",
  "bear",
  "ponzi",
  "too big to fail",
  "subprime",
  "low",
  "bottom",
];
